### ISSUE TITLE
[Bug] Conditional Dependencies Not Working with Helm API Version Lower Than v2

### ISSUE THREAD

**Issue by weidaolee** [monographdb/monograph-charts#4]
### Description
Conditional dependencies in Helm charts do not work as expected when the chart's `apiVersion` is lower than `v2`. This causes dependencies, like `cert-manager`, to be installed regardless of the conditional flag set in `values.yaml` (e.g., `cert-manager.enabled`).

### Steps to Reproduce
1. Create a Helm chart with `apiVersion: v1` in `Chart.yaml`.
2. Add a dependency with a conditional enablement in `Chart.yaml`, such as:
   ```yaml
   apiVersion: v1
   dependencies:
     - name: cert-manager
       version: "<version>"
       repository: "https://charts.jetstack.io"
       condition: cert-manager.enabled
   ``` 
3. Set the conditional flag in `values.yaml`:
   ```bash
   cert-manager:
   enabled: false
   ```
4. Run
   ```bash
   helm package monograph-operator
   helm install monograph-operator -n monograph-operator-system monograph-operator-1.0.4.tgz --set keepCrds=false
   ```
### Expected Behavior
The dependent chart (`cert-manager`) should only be installed if the enabled flag is set to `true`.
### Actual Behavior
The dependent chart is installed regardless of the enabled flag's value.
